### ISSUE TITLE
Try breaking single eQTL workflow into multiple small workflows based on data locality for multi-site execution

### ISSUE THREAD

**Issue by shukapoo** [CINECA-project/wp4-federated-joint-cohort-analysis#3]

**Comment by kauralasoo** [comment]
I have made a first attempt on this: https://github.com/CINECA-project/wp4-federated-joint-cohort-analysis/commit/b16fafc3cc1ae159a357a5985881b779dfac8fab

**Comment by kauralasoo** [comment]
Hi Kirill,
Is there anything else that you would need right now? The minimal workflow is designed to mimic the part of the analysis that is run at each cohort separately and it has two processes where the second process uses the results of the first process. The two reference files are currently in Dropbox, because I do not have an easy access to a public FTP server, but these can in principle be uploaded anywhere.

**Comment by tskir** [comment]
I was just going through all open issues and was unsure on the status of this, since it was still open. Indeed, looks like the workflow is in order, I'll try running it as part of #16. If I run into any problems, I'll open follow up issues about them specifically. For now, closing this one, thanks!
